apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: chartmuseum-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  backendType: vault
  vaultMountPoint: kubernetes/kubefirst
  vaultRole: external-secrets
  kvVersion: 2
  data:
    - name: AWS_ACCESS_KEY_ID
      key: secret/data/chartmuseum
      property: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      key: secret/data/chartmuseum
      property: AWS_SECRET_ACCESS_KEY
    - name: BASIC_AUTH_USER
      key: secret/data/chartmuseum
      property: BASIC_AUTH_USER
    - name: BASIC_AUTH_PASS
      key: secret/data/chartmuseum
      property: BASIC_AUTH_PASS
