apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-runner
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  backendType: vault
  vaultMountPoint: kubernetes/kubefirst # todo: kubefirst -> kubefirst
  vaultRole: external-secrets
  kvVersion: 2
  data:
    - name: runner-token
      key: secret/data/gitlab-runner
      property: RUNNER_TOKEN
    - name: runner-registration-token
      key: secret/data/gitlab-runner
      property: RUNNER_REGISTRATION_TOKEN
