apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-components
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  project: default
  source:
    repoURL: https://gitlab.starter.kubefirst.com/kubefirst/gitops.git
    path: components/keycloak
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
--- 
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: keycloak-secrets-to-vault
#   annotations:
#     argocd.argoproj.io/sync-wave: "14"
#     # argocd.argoproj.io/hook: PostSync # don't PostSync, vault doesn't finish sync while waiting for pods to be running which requires this job
#     # argocd.argoproj.io/hook-delete-policy: HookSucceeded
# spec:
#   template:
#     spec:
#       containers:
#         # todo adjust node permissions to be adequate for geting a kubeconfig in terraform - manually adding in console
#       - name: keycloak-secrets-to-vault
#         image: kubefirst/kubefirst-builder:spike
#         # todo need to rename `kubefirst-admin` to `KubernetesAdmin`
#         command:
#         - /bin/bash
#         - -c
#         - |
#           sleep 30
#           aws eks update-kubeconfig --name kubefirst --region  us-east-1
#           kubectl -n vault exec vault-0 -- vault operator init -format=json > cluster-keys.json
#         # todo remove this envFrom and assume role
#         # todo remove this envFrom and assume role
#         envFrom:
#         - secretRef:
#             name: aws-creds
#       restartPolicy: Never
#   backoffLimit: 2