apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  backendType: vault
  vaultMountPoint: kubernetes/kubefirst
  vaultRole: external-secrets
  kvVersion: 2
  data:
  - name: KEYCLOAK_ADMIN_PASSWORD
    key: secret/data/keycloak
    property: KEYCLOAK_ADMIN_PASSWORD
  - name: KEYCLOAK_MANAGEMENT_PASSWORD
    key: secret/data/keycloak
    property: KEYCLOAK_MANAGEMENT_PASSWORD
  - name: KEYCLOAK_DATABASE_PASSWORD
    key: secret/data/keycloak
    property: KEYCLOAK_DATABASE_PASSWORD
