gitlabUrl: @GITLAB_URL@
runnerRegistrationToken: @RUNNER_REGISTRATION_TOKEN@
nodeSelector:
  workload: mgmt
rbac:
  clusterWideAccess: true
  create: true
runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        image = "ubuntu:20.04"
        privileged = true
      [[runners.kubernetes.volumes.empty_dir]]
        name = "docker-certs"
        mount_path = "/certs/client"
        medium = "Memory"
  name: gitlab-runner
  privileged: true
unregisterRunners: true