apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ template "metaphor.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  backendType: vault
  vaultMountPoint: "kubernetes/{{ .Values.vaultMountPoint}}"
  vaultRole: external-secrets
  kvVersion: 2
  data:
    - name: SECRET_ONE
      key: "secret/data/{{ .Values.vaultSecretPath }}"
      property: SECRET_ONE
    - name: SECRET_TWO
      key: "secret/data/{{ .Values.vaultSecretPath }}"
      property: SECRET_TWO
