apiVersion: batch/v1
kind: Job
metadata:
  name: nebulous
spec:
  template:
    spec:
      containers:
      - name: nebulous
        image: kubefirst/nebulous:0.1-rc2
        command: ["sh", "-c", "/scripts/nebulous/init.sh" ]
        # command: ["/bin/sh"]
        # args: ["-c", "/scripts/nebulous/init.sh"]
        envFrom:
        - secretRef:
            name: nebulous-secrets
        - configMapRef:
            name: nebulous-cm
      restartPolicy: Never
  backoffLimit: 4

