metaphor:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: metaphor-development.starter.kubefirst.com
        paths:
          - /
    tls:
    - secretName: metaphor-tls
      hosts:
        - metaphor-development.starter.kubefirst.com
  vaultMountPoint: kubefirst
  vaultSecretPath: metaphor/development
