apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis-components
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  project: default
  source:
    repoURL: https://gitlab.mgmt.kubefirst.com/kubefirst/gitops.git
    path: components/atlantis
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: atlantis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
